#!/usr/bin/env bash

state=$(cat /sys/class/power_supply/BAT0/status)
cap=$(cat /sys/class/power_supply/BAT0/capacity)
if [ $state = "Charging" ]; then
	echo "ﮣ $cap%"
elif [ $state = "Full" ]; then
  echo "ﮣ"
elif [ "$cap" -gt "50" ]; then
  echo " "
elif [ $cap = "50" ]; then
  echo " "
elif [ "$cap" -gt "20" ]; then
  echo " "
else
	echo " "
  dunstify -u low -r "20" "Battery Low $cap%" "Please Charge ﮣ"
fi
