#!/usr/bin/env bash

state=$(cat /sys/class/power_supply/BAT0/status)
cap=$(cat /sys/class/power_supply/BAT0/capacity)
if [ $state = "Charging" ]; then
	echo "ﮣ"
elif [ "$cap" -gt "50" ]; then
  echo ""
elif [ $cap = "50" ]; then
  echo ""
elif [ "$cap" -gt "20" ]; then
  echo " $cap"
else
	echo " "
#  dunstify -a "Battery" -u low -r "20" "Battery Low $cap%" "Please Charge "
fi
