#!/usr/bin/env bash
volstat="$(amixer get Master)"

echo "$volstat" | grep "\[off\]" >/dev/null && printf "婢\\n" && exit

vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed "s/[^0-9]*//g;1q")

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -lt "30" ]; then
	icon=""
else
	icon="墳"
fi

echo "$icon"
